### ISSUE TITLE
Help Me!!!

### ISSUE THREAD

**Issue by div-ru** [sanguohot/hellocontract#1]
I found your message https://github.com/fyne-io/fyne/issues/311#issuecomment-564411832. Help me, please!!! I do not understand how to use GetPos and SetPos without changing the source code of **fyne**. If you have done so, please share an example. Thank you!!!

**Comment by sanguohot** [comment]
@div-ru 
I have simply changed the source code.
You can take a look at my commit [sanguohot/fyne/commit/7734c6408de424a59692f852fb4407f881800721](https://github.com/sanguohot/fyne/commit/7734c6408de424a59692f852fb4407f881800721)

**Comment by div-ru** [comment]
Thank you very much for the answer. That was helpful. Best regards, Ivan.

**Comment by 2096779623** [comment]
@sanguohot 现在fyne升级到了v2，之前的方法好像失效了（）
